version: "3.8"
services:
  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./customer/.env.dev

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - customer
    volumes:
      - .:/app
      - /app/gateway/node_modules
    env_file:
      - ./gateway/.env.dev

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - gateway
      - customer
      - db
    ports:
      - 80:80
volumes:
  pgdata:
