version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    networks:
      - ecommerce

  order:
    build: ./order
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/orderdb
    env_file:
      - ./order/.env
    networks:
      - ecommerce

  product:
    build: ./product
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/productdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./product/.env
    networks:
      - ecommerce

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    networks:
      - ecommerce

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db11
    networks:
      - ecommerce

  redis:
    image: redis:7.4.0-alpine
    environment:
      - REDIS_URL=redis://redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce

networks:
  ecommerce:

volumes:
  mongo-data:
